import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'pt', 'hu', 'it', 'ro', 'es', 'tr'];

  String get languageCode => locale.toString();
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? ptText = '',
    String? huText = '',
    String? itText = '',
    String? roText = '',
    String? esText = '',
    String? trText = '',
  }) =>
      [enText, ptText, huText, itText, roText, esText, trText][languageIndex] ??
      '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      FFLocalizations.languages().contains(locale.toString());

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Home
  {
    'ckwfwwmv': {
      'en': 'ActiveGames4Change',
      'es': 'ActiveGames4Change',
      'hu': 'ActiveGames4Change',
      'it': 'ActiveGames4Change',
      'pt': 'ActiveGames4Change',
      'ro': 'ActiveGames4Change',
      'tr': 'ActiveGames4Change',
    },
    'ffh9le7o': {
      'en':
          'The European Commission\'s support for the production of this application does not constitute an endorsement of the contents, which reflect the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'lxyzam5x': {
      'en':
          'The European Commission\'s support for the production of this application does not constitute an endorsement of the contents, which reflect the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.',
      'es':
          'El apoyo de la Comisión Europea para la producción de esta publicación no constituye una aprobación del\ncontenido, el cual refleja únicamente las opiniones de los autores, y la Comisión no se hace responsable del\nuso que pueda hacerse de la información contenida en la misma.',
      'hu':
          'Az Európai Bizottság támogatása ezen kiadvány elkészítéséhez nem jelenti a tartalom jóváhagyását, amely kizárólag a szerzők álláspontját tükrözi, valamint a Bizottság nem tehető felelőssé ezen információk\nbárminemű felhasználásáért.\n',
      'it':
          'Il sostegno della Commissione europea alla produzione di questa pubblicazione non costituisce\nun\'approvazione del contenuto, che riflette esclusivamente il punto di vista degli autori, e la Commissione\nnon può essere ritenuta responsabile per l\'uso che può essere fatto delle informazioni ivi contenute.',
      'pt':
          'O apoio da Comissão Europeia à produção desta publicação não constitui um aval do seu conteúdo, que reflete unicamente o ponto de vista dos autores, e a Comissão não pode ser considerada responsável por eventuais utilizações que possam ser feitas com as informações nela contidas.',
      'ro':
          'Sprijinul acordat de Comisia Europeană pentru elaborarea acestei publicații nu constituie o aprobare a\nconținutului, care reflectă doar opiniile autorilor, iar Comisia nu poate fi trasă la răspundere pentru orice utilizare a informațiilor conținute în aceasta.',
      'tr':
          'The European Commission\'s support for the production of this application does not constitute an endorsement of the contents, which reflect the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.',
    },
    '0v9k30h8': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
    '6kkbb74n': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // Login
  {
    '5wuf7hn4': {
      'en': 'ActiveGames4Change',
      'es': 'ActiveGames4Change',
      'hu': 'ActiveGames4Change',
      'it': 'ActiveGames4Change',
      'pt': 'ActiveGames4Change',
      'ro': 'ActiveGames4Change',
      'tr': 'ActiveGames4Change',
    },
    'bs24ynjr': {
      'en': 'Login',
      'es': 'Acceso',
      'hu': 'Belépés',
      'it': 'Login',
      'pt': 'Login',
      'ro': 'Autentificare',
      'tr': 'Oturum Aç',
    },
    '9i0n3h5k': {
      'en': 'Login',
      'es': 'Acceso',
      'hu': 'Belépés',
      'it': 'Login',
      'pt': 'Login',
      'ro': 'Autentificare',
      'tr': 'Oturum Aç',
    },
    'mkwjj6n0': {
      'en': 'Email Address',
      'es': 'Correo Electrónico',
      'hu': 'Email cím',
      'it': 'Indirizzo E-mail',
      'pt': 'Endereço de Email',
      'ro': 'Adresa de E-mail',
      'tr': 'E-posta',
    },
    'yj3j6lon': {
      'en': 'Password',
      'es': 'Contraseña',
      'hu': 'Jelszó',
      'it': 'Password',
      'pt': 'Palavra Passe',
      'ro': 'Parola',
      'tr': 'Parola',
    },
    '8g0mjyo6': {
      'en': 'Login',
      'es': 'Acceso',
      'hu': 'Belépés',
      'it': 'Login',
      'pt': 'Login',
      'ro': 'Autentificare',
      'tr': 'Oturum Aç',
    },
    's3wct76l': {
      'en': 'Recover Password',
      'es': 'Recuperar Contraseña',
      'hu': 'Jelszó helyreállítása',
      'it': 'Recupera la Password',
      'pt': 'Recuperar senha',
      'ro': 'Recuperează Parola',
      'tr': 'Parolanızı mı Unuttunuz?',
    },
    'vgwlou1d': {
      'en':
          'The European Commission\'s support for the production of this application does not constitute an endorsement of the contents, which reflect the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    '7jdak33z': {
      'en':
          'The European Commission\'s support for the production of this application does not constitute an endorsement of the contents, which reflect the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.',
      'es':
          'El apoyo de la Comisión Europea para la producción de esta publicación no constituye una aprobación del\ncontenido, el cual refleja únicamente las opiniones de los autores, y la Comisión no se hace responsable del\nuso que pueda hacerse de la información contenida en la misma.',
      'hu':
          'Az Európai Bizottság támogatása ezen kiadvány elkészítéséhez nem jelenti a tartalom jóváhagyását, amely kizárólag a szerzők álláspontját tükrözi, valamint a Bizottság nem tehető felelőssé ezen információk\nbárminemű felhasználásáért.',
      'it':
          'Il sostegno della Commissione europea alla produzione di questa pubblicazione non costituisce\nun\'approvazione del contenuto, che riflette esclusivamente il punto di vista degli autori, e la Commissione\nnon può essere ritenuta responsabile per l\'uso che può essere fatto delle informazioni ivi contenute.',
      'pt':
          'O apoio da Comissão Europeia à produção desta publicação não constitui um aval do seu conteúdo, que reflete unicamente o ponto de vista dos autores, e a Comissão não pode ser considerada responsável por eventuais utilizações que possam ser feitas com as informações nela contidas.',
      'ro':
          'Sprijinul acordat de Comisia Europeană pentru elaborarea acestei publicații nu constituie o aprobare a\nconținutului, care reflectă doar opiniile autorilor, iar Comisia nu poate fi trasă la răspundere pentru orice utilizare a informațiilor conținute în aceasta.',
      'tr':
          'The European Commission\'s support for the production of this application does not constitute an endorsement of the contents, which reflect the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.',
    },
    '04zszu73': {
      'en': 'Create Account',
      'es': 'Crear una Cuenta',
      'hu': 'Fiók létrehozása',
      'it': 'Creare un Account',
      'pt': 'Criar uma Conta',
      'ro': 'Creează Cont',
      'tr': 'Kaydet',
    },
    'q13dg6mo': {
      'en': 'Create Account',
      'es': 'Crear una Cuenta',
      'hu': 'Fiók létrehozása',
      'it': 'Creare un Account',
      'pt': 'Criar uma Conta',
      'ro': 'Creează Cont',
      'tr': 'Hesap Oluştur',
    },
    'yl81vmby': {
      'en': 'Email Address',
      'es': 'Correo Electrónico',
      'hu': 'Email Cím',
      'it': 'Indirizzo E-mail',
      'pt': 'Endereço de Email',
      'ro': 'Adresa de E-mail',
      'tr': 'E-posta',
    },
    '2toybxh7': {
      'en': 'Password',
      'es': 'Contraseña',
      'hu': 'Jelszó',
      'it': 'Parola ',
      'pt': 'Senha',
      'ro': 'Parola',
      'tr': 'Parola',
    },
    'czq9mic6': {
      'en': 'Confirm Password',
      'es': 'Confirmar Contraseña',
      'hu': 'Jelszó Megerősítése',
      'it': 'Conferma Password',
      'pt': 'Confirme sua Senha',
      'ro': 'Confirmă Parola',
      'tr': 'Parolayı Onaylayınız',
    },
    'yc4czujm': {
      'en': 'Create Account',
      'es': 'Crear una Cuenta',
      'hu': 'Fiók létrehozása',
      'it': 'Creare un Account',
      'pt': 'Criar uma Conta',
      'ro': 'Creează Cont',
      'tr': 'Kaydet',
    },
    'xt5o5bsg': {
      'en': 'Home',
      'es': ' Inicio',
      'hu': 'Itthon',
      'it': 'Home',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // Game
  {
    'i63beppe': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    '658qpixq': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // Aclass
  {
    '64dib1x2': {
      'en': 'Class',
      'es': 'Clase',
      'hu': 'Osztály',
      'it': 'Classe',
      'pt': 'Turma',
      'ro': 'Clasă',
      'tr': 'Sınıf',
    },
    'fkkd6msn': {
      'en': 'New',
      'es': 'Nuevo',
      'hu': 'Új',
      'it': 'Nuovo',
      'pt': 'Novo',
      'ro': 'Nou',
      'tr': 'Yeni',
    },
    'hc17u6s1': {
      'en': 'View',
      'es': 'Vista',
      'hu': 'Kilátás',
      'it': 'Visualizzazione',
      'pt': 'Visualizar',
      'ro': 'Vedere',
      'tr': ' Görüntüle',
    },
    'aszdb7ob': {
      'en': 'Data View',
      'es': '',
      'hu': '',
      'it': '',
      'pt': 'Dados',
      'ro': '',
      'tr': '',
    },
    'tj2ob8ky': {
      'en': 'Class Assessment',
      'es': 'Evaluación de la Clase',
      'hu': 'Osztály Értékelése',
      'it': 'Valutazione di Classe',
      'pt': 'Avaliação da Turma',
      'ro': 'Evaluarea Clasei',
      'tr': 'Sınıfı Değerlendirmesi',
    },
    '0gcaytv4': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // RegisteList
  {
    'rfujyhef': {
      'en': 'List Class',
      'es': 'Lista de Clases',
      'hu': 'Osztály listája',
      'it': 'Elenco di Classe',
      'pt': 'Listar Turma',
      'ro': 'Listă Clasa',
      'tr': 'Sınıf Listesi',
    },
    'ug80lrg8': {
      'en': 'List Class',
      'es': 'Lista de Clases',
      'hu': 'Osztály listája',
      'it': 'Elenco di Classe',
      'pt': 'Listar Turma',
      'ro': 'Listă Clasa',
      'tr': 'Sınıf Listesi',
    },
    'gxoc2hky': {
      'en': 'Delete',
      'es': 'Borrar',
      'hu': 'Töröl',
      'it': 'Eliminare',
      'pt': 'Eliminar',
      'ro': 'Șterge',
      'tr': 'Silmek',
    },
    'mg7jasgb': {
      'en': 'Students',
      'es': 'Estudiantes',
      'hu': 'Diákok',
      'it': 'Studenti',
      'pt': 'Alunos',
      'ro': 'Elevi',
      'tr': 'Öğrenciler',
    },
    'pn2zr4l8': {
      'en': 'Create Class',
      'es': 'Crear Clase',
      'hu': 'Osztály létrehozása',
      'it': 'Crea Classe',
      'pt': 'Criar Turma',
      'ro': 'Creați o Clasă',
      'tr': 'Sınıf Oluştur',
    },
    'r9ylvh2k': {
      'en': 'Create Class',
      'es': 'Crear Clase',
      'hu': 'Osztály létrehozása',
      'it': 'Crea Classe',
      'pt': 'Criar Turma',
      'ro': 'Creați o Clasă',
      'tr': 'Sınıf Oluştur',
    },
    'lk2n200u': {
      'en': 'Name',
      'es': 'Nombre',
      'hu': 'Név',
      'it': 'Nome',
      'pt': 'Nome',
      'ro': 'Nume',
      'tr': 'İsim',
    },
    'wakm1xvd': {
      'en': 'Register',
      'es': 'Registro',
      'hu': 'Regisztráció',
      'it': 'Registrati',
      'pt': 'Registar',
      'ro': 'Inregistreaza-te',
      'tr': 'Kayıt Olmak',
    },
    'ph6pxwu9': {
      'en': 'Add Student',
      'es': 'Agregar Estudiante',
      'hu': 'Diák Hozzáadása',
      'it': 'Aggiungi Studente',
      'pt': 'Adicionar Aluno',
      'ro': 'Adăugați Student',
      'tr': 'Öğrenci Ekle',
    },
    'wbgft18b': {
      'en': 'Add Student',
      'es': 'Agregar Estudiante',
      'hu': 'Diák Hozzáadása',
      'it': 'Aggiungi Studente',
      'pt': 'Adicionar Aluno',
      'ro': 'Adăugați Student',
      'tr': 'Öğrenci Ekle',
    },
    '9zc7icge': {
      'en': 'Add',
      'es': 'Agregar',
      'hu': 'Hozzáadás',
      'it': 'Aggiungere',
      'pt': 'Adicionar',
      'ro': 'Adăuga',
      'tr': 'Ekle',
    },
    'cvj8zfes': {
      'en': 'Register Class',
      'es': 'Registrar la Clase',
      'hu': 'Regisztráljon Osztályt',
      'it': 'Registra Classe',
      'pt': 'Registar Turma',
      'ro': 'Înregistrați Clasa',
      'tr': 'Sınıfı Kaydet',
    },
    '3xo6itbb': {
      'en': 'Class',
      'es': 'Clase',
      'hu': 'Osztály',
      'it': 'Classe',
      'pt': 'Turma',
      'ro': 'Clasă',
      'tr': 'Sınıf',
    },
  },
  // ClassAviewPage
  {
    'yxpejyu0': {
      'en': 'Self-awareness?',
      'es': '¿Autoconciencia?',
      'hu': 'Öntudat?',
      'it': 'Autocoscienza?',
      'pt': 'Autoconsciência?',
      'ro': 'Constiinta de sine?',
      'tr': 'Öz- farkındalık?',
    },
    'ftdq8ckj': {
      'en': 'Self-management?',
      'es': '¿Autogestión?',
      'hu': 'Önálló gazdálkodás?',
      'it': 'Autogestione?',
      'pt': 'Auto Gerenciamento?',
      'ro': 'Managementul de sine?',
      'tr': 'Öz-yönetim?',
    },
    'ccrdtun7': {
      'en': 'Responsible decision making?',
      'es': '¿Toma de decisiones responsable?',
      'hu': 'Felelős döntéshozatal?',
      'it': 'Decisione responsabile?',
      'pt': 'Tomada de decisão responsável?',
      'ro': 'Luare responsabilă a deciziilor?',
      'tr': 'Sorumlu karar verme?',
    },
    'y2bwhrel': {
      'en': 'Relationship skills?',
      'es': '¿Habilidad de relación?',
      'hu': 'Párkapcsolati készségek?',
      'it': 'Abilità relazionali?',
      'pt': 'Habilidades de relacionamento?',
      'ro': 'Abilități de relație?',
      'tr': 'İlişki Becerileri?',
    },
    'tin1jyt4': {
      'en': 'Social awareness?',
      'es': '¿Conciencia social?',
      'hu': 'Társadalmi tudatosság?',
      'it': 'Consapevolezza sociale?',
      'pt': 'Consciência social?',
      'ro': 'Constientizare sociala?',
      'tr': 'Sosyal Farkındalık?',
    },
    '6ig1k875': {
      'en': 'Delete',
      'es': 'Borrar',
      'hu': 'Töröl',
      'it': 'Eliminare',
      'pt': 'Excluir',
      'ro': 'Șterge',
      'tr': 'Silmek',
    },
    'q6p6evok': {
      'en': 'View Assessment',
      'es': 'Ver evaluación',
      'hu': 'Értékelés megtekintése',
      'it': 'Visualizza valutazione',
      'pt': 'Ver Avaliação',
      'ro': 'Vedeți evaluarea',
      'tr': 'Değerlendirmeyi Görüntüle',
    },
    'sxz1j0ig': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // Astudent
  {
    's6kk1znd': {
      'en': 'Class',
      'es': 'Clase',
      'hu': 'Osztály',
      'it': 'Classe',
      'pt': 'Turma',
      'ro': 'Clasă',
      'tr': 'Sınıf',
    },
    'v2ahwzl2': {
      'en': 'View',
      'es': 'Vista',
      'hu': 'Kilátás',
      'it': 'Visualizzazione',
      'pt': 'Visualizar',
      'ro': 'Vedere',
      'tr': 'görüş',
    },
    '0xosnbnd': {
      'en': 'Student Assessment',
      'es': 'Evaluación del Estudiante',
      'hu': 'Diákértékelés',
      'it': 'Valutazione Degli Studenti',
      'pt': 'Avaliação do Aluno',
      'ro': 'Evaluarea Elevilor',
      'tr': 'Öğrenci değerlendirmesi',
    },
    'kepkn1v5': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // StudentAcreatPage
  {
    'a2b0ytv7': {
      'en': 'WEMWBS',
      'es': 'WEMWBS',
      'hu': 'WEMWBS',
      'it': 'WEMWBS',
      'pt': 'WEMWBS',
      'ro': 'WEMWBS',
      'tr': 'WEMWBS',
    },
    'gugql2bc': {
      'en': 'I’ve been feeling optimistic about the future?',
      'es': '¿Me he sentido optimista respecto al futuro?',
      'hu': 'Optimista vagyok a jövőt illetően?',
      'it': 'Mi sono sentito ottimista riguardo al futuro?',
      'pt': 'Tenho-me sentido otimista em relação ao futuro?',
      'ro': 'M-am simțit optimist cu privire la viitor?',
      'tr': 'Gelecekle ilgili iyimserim?',
    },
    'ngp8bexb': {
      'en': 'I’ve been feeling useful?',
      'es': '¿Me he sentido útil?',
      'hu': 'Hasznosnak éreztem magam?',
      'it': 'Mi sono sentito utile?',
      'pt': 'Tenho-me sentido útil?',
      'ro': 'M-am simțit util?',
      'tr': 'Kendimi işe yarar (faydalı) hissediyorum?',
    },
    'tdoiih1d': {
      'en': 'I’ve been feeling relaxed?',
      'es': '¿Me he sentido relajado/a?',
      'hu': 'Kipihentnek éreztem magam?',
      'it': 'Mi sono sentito rilassato?',
      'pt': 'Tenho-me sentido relaxado?',
      'ro': 'M-am simțit relaxat?',
      'tr': 'Kendimi rahatlamış hissediyorum?',
    },
    'ov7pqg28': {
      'en': 'I’ve been feeling interested in other people?',
      'es': '¿He sentido interés por los demás?',
      'hu': 'Érdeklődtem mások iránt?',
      'it': 'Mi sono sentito interessato ad altre persone?',
      'pt': 'Tenho-me sentido interessado pelas\noutras pessoas?',
      'ro': 'M-am simțit interesat de alți oameni?',
      'tr': 'Diğer insanlara karşı ilgiliyim?',
    },
    '0lg97b79': {
      'en': 'I’ve had energy to spare?',
      'es': '¿He tenido energía de sobra?',
      'hu': 'Volt tartalék energiám?',
      'it': 'Ho avuto energia da risparmiare?',
      'pt': 'Tenho tido energia de sobra?',
      'ro': 'Am avut energie de pierdut?',
      'tr': 'Farklı işlere zaman ayırabilecek enerjim var?',
    },
    'uk1aszww': {
      'en': 'I’ve been dealing with problems well?',
      'es': '¿He afrontado bien los problemas?',
      'hu': 'Jól kezeltem a problémákat?',
      'it': 'Ho affrontato bene i problemi?',
      'pt': 'Tenho lidado bem com os problemas?',
      'ro': 'M-am descurcat bine cu problemele?',
      'tr': 'Sorunlarla iyi bir şekilde başa çıkabilirim?',
    },
    '0ru7hiz7': {
      'en': 'I’ve been thinking clearly?',
      'es': '¿He podido pensar con claridad?',
      'hu': 'Tisztán gondolkodtam?',
      'it': 'Ho pensato chiaramente?',
      'pt': 'Tenho conseguido pensar de forma clara?',
      'ro': 'M-am gândit clar?',
      'tr': 'Açık ve net bir şekilde düşünebiliyorum?',
    },
    'm9okw09e': {
      'en': 'I’ve been feeling good about myself?',
      'es': '¿Me he sentido bien conmigo mismo/a?',
      'hu': 'Jól éreztem magam?',
      'it': 'Mi sono sentito bene con me stesso?',
      'pt': 'Tenho-me sentido bem comigo mesmo?',
      'ro': 'M-am simțit bine cu mine?',
      'tr': 'Kendimden memnunum?',
    },
    'hf9om67v': {
      'en': 'I’ve been feeling close to other people?',
      'es': '¿Me he sentido cercano/a a los demás?',
      'hu': 'Közel éreztem magam másokhoz?',
      'it': 'Mi sono sentito vicino ad altre persone?',
      'pt': 'Tenho-me sentido próximo de outras\npessoas?',
      'ro': 'M-am simțit aproape de alți oameni?',
      'tr': 'Kendimi diğer insanlara yakın hissediyorum?',
    },
    'gh2x5h5k': {
      'en': 'I’ve been feeling confident?',
      'es': '¿Me he sentido seguro/a (con confianza)?',
      'hu': 'Magabiztosnak éreztem magam?',
      'it': 'Mi sono sentito sicuro?',
      'pt': 'Tenho-me sentido confiante?',
      'ro': 'M-am simțit încrezător?',
      'tr': 'Kendime güveniyorum?',
    },
    'qxv845xt': {
      'en': 'I’ve been able to make up  my own mind  about things?',
      'es': '¿He sido capaz de tomar mis propias decisiones?',
      'hu': 'El tudtam dönteni a saját véleményemet a dolgokról?',
      'it': 'Sono stato in grado di prendere una decisione sulle cose?',
      'pt': 'Tenho sido capaz de construir as minhas opiniões sobre as coisas?',
      'ro': 'Am reușit să mă hotăresc despre lucruri?',
      'tr': 'Kendi kararlarımı kendim verebiliyorum?',
    },
    'xmnf9q9t': {
      'en': 'I’ve been feeling loved?',
      'es': '¿Me he sentido querido/a?',
      'hu': 'Szeretve éreztem magam?',
      'it': 'Mi sono sentito amato?',
      'pt': 'Tenho-me sentido amado?',
      'ro': 'M-am simțit iubit?',
      'tr': 'Sevildiğimi hissediyorum?',
    },
    'y52ex6n2': {
      'en': 'I’ve been interested in new things?',
      'es': '¿Me he interesado por cosas nuevas?',
      'hu': 'Érdekeltek az új dolgok?',
      'it': 'Sono stato interessato a cose nuove?',
      'pt': 'Tenho-me sentido interessado em coisas novas?',
      'ro': 'M-au interesat lucruri noi?',
      'tr': 'Yeni şeylere karşı ilgiliyim?',
    },
    'eup6nzf7': {
      'en': 'I’ve been feeling cheerful?',
      'es': '¿Me he sentido alegre?',
      'hu': 'Jókedvűnek éreztem magam?',
      'it': 'Mi sono sentito allegro?',
      'pt': 'Tenho-me sentido alegre?',
      'ro': 'M-am simțit vesel?',
      'tr': 'Neşeli hissediyorum?',
    },
    'qysyzfkq': {
      'en': 'Save',
      'es': 'Guardar',
      'hu': 'Megment',
      'it': 'Salva',
      'pt': 'Salve ',
      'ro': 'salva',
      'tr': 'Kaydetmek',
    },
    'd0etwovn': {
      'en': 'Skills',
      'es': 'Competencias',
      'hu': 'Készségek',
      'it': 'Competenze',
      'pt': 'Habilidades',
      'ro': 'Aptitudini',
      'tr': 'Yetenekler',
    },
    'c2x7hurt': {
      'en': 'Assessment',
      'es': 'Evaluación',
      'hu': 'Értékelés',
      'it': 'Valutazione',
      'pt': 'Avaliação',
      'ro': 'Evaluare',
      'tr': 'Değerlendirme',
    },
    'kdmk6xfm': {
      'en': 'Self-awareness?',
      'es': '¿Autoconciencia?',
      'hu': 'Öntudat?',
      'it': 'Autocoscienza?',
      'pt': 'Autoconsciência?',
      'ro': 'Constiinta de sine?',
      'tr': 'Öz farkındalık?',
    },
    'v70wm5xt': {
      'en': 'Self-management?',
      'es': '¿Autogestión?',
      'hu': 'Önálló gazdálkodás?',
      'it': 'Autogestione?',
      'pt': 'Auto Gerenciamento?',
      'ro': 'Managementul de sine?',
      'tr': 'Öz yönetim?',
    },
    'h4o4j0f8': {
      'en': 'Responsible decision making?',
      'es': '¿Toma de decisiones responsable?',
      'hu': 'Felelős döntéshozatal?',
      'it': 'Decisione responsabile?',
      'pt': 'Tomada de decisão responsável?',
      'ro': 'Luare responsabilă a deciziilor?',
      'tr': 'Sorumlu karar verme?',
    },
    '7u6nqtr9': {
      'en': 'Relationship skills?',
      'es': '¿Habilidades de relación?',
      'hu': 'Párkapcsolati készségek?',
      'it': 'Abilità relazionali?',
      'pt': 'Habilidades de relacionamento?',
      'ro': 'Abilități de relație?',
      'tr': 'İlişki becerileri?',
    },
    'mdinwfx4': {
      'en': 'Social awareness?',
      'es': '¿Conciencia social?',
      'hu': 'Társadalmi tudatosság?',
      'it': 'Consapevolezza sociale?',
      'pt': 'Consciência social?',
      'ro': 'Constientizare sociala?',
      'tr': 'Sosyal farkındalık mı?',
    },
    'jpc66zn9': {
      'en': 'Description',
      'es': 'Descripción',
      'hu': 'Leírás',
      'it': 'Descrizione',
      'pt': 'Descrição',
      'ro': 'Descriere',
      'tr': 'Tanım',
    },
    'yc6nbdxg': {
      'en': 'Save',
      'es': 'Guardar',
      'hu': 'Megment',
      'it': 'Salva',
      'pt': 'Salve ',
      'ro': 'salva',
      'tr': 'Gönder',
    },
    'yxsgvtcy': {
      'en': 'Create  Assessment',
      'es': 'Crear evaluación',
      'hu': 'Készítsen értékelést',
      'it': 'Crea valutazione',
      'pt': 'Criar avaliação',
      'ro': 'Creați evaluarea',
      'tr': 'Değerlendirme Oluştur',
    },
    '8phugr53': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // AstudentView
  {
    'fw2t40xh': {
      'en': 'Student List',
      'es': 'Lista de Estudiantes',
      'hu': 'Diáklista',
      'it': 'Elenco Studenti',
      'pt': 'Lista de Alunos',
      'ro': 'Lista Studenților',
      'tr': 'Öğrenci Listesi',
    },
    'boblci7d': {
      'en': 'New',
      'es': 'Nuevo',
      'hu': 'Új',
      'it': 'Nuovo',
      'pt': 'Novo',
      'ro': 'Nou',
      'tr': 'Yeni',
    },
    '0krl8lnn': {
      'en': 'View',
      'es': 'Vista',
      'hu': 'Kilátás',
      'it': 'Visualizzazione',
      'pt': 'Visualizar',
      'ro': 'Vedere',
      'tr': 'Görüntüle',
    },
    'ub9fu0ck': {
      'en': 'Data view',
      'es': '',
      'hu': '',
      'it': '',
      'pt': 'Dados',
      'ro': '',
      'tr': '',
    },
    'uomonef4': {
      'en': 'Delete',
      'es': 'Borrar',
      'hu': 'Töröl',
      'it': 'Eliminare',
      'pt': 'Excluir',
      'ro': 'Șterge',
      'tr': 'Silmek',
    },
    '84sawfdl': {
      'en': 'Student Assessment',
      'es': 'Evaluación del Estudiante',
      'hu': 'Diákértékelés',
      'it': 'Valutazione Degli Studenti',
      'pt': 'Avaliação do Aluno',
      'ro': 'Evaluarea Elevilor',
      'tr': 'Öğrenci Değerlendirmesi',
    },
    '1u2a7ota': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // StudentAviewPage
  {
    '6m22d1qy': {
      'en': 'WEMWBS',
      'es': 'WEMWBS',
      'hu': 'WEMWBS',
      'it': 'WEMWBS',
      'pt': 'WEMWBS',
      'ro': 'WEMWBS',
      'tr': 'WEMWBS',
    },
    'ajh4fist': {
      'en': 'I’ve been feeling optimistic about the future?',
      'es': '¿Me he sentido optimista respecto al futuro?',
      'hu': 'Optimista vagyok a jövőt illetően?',
      'it': 'Mi sono sentito ottimista riguardo al futuro?',
      'pt': 'Tenho-me sentido otimista em relação ao futuro?',
      'ro': 'M-am simțit optimist cu privire la viitor?',
      'tr': 'Gelecekle ilgili iyimserim?',
    },
    'v81noglz': {
      'en': 'I’ve been feeling useful?',
      'es': '¿Me he sentido útil?',
      'hu': 'Hasznosnak éreztem magam?',
      'it': 'Mi sono sentito utile?',
      'pt': 'Tenho-me sentido útil?',
      'ro': 'M-am simțit util?',
      'tr': 'Kendimi işe yarar (faydalı) hissediyorum?',
    },
    'bhmb4s8d': {
      'en': 'I’ve been feeling relaxed?',
      'es': '¿Me he sentido relajado/a?',
      'hu': 'Kipihentnek éreztem magam?',
      'it': 'Mi sono sentito rilassato?',
      'pt': 'Tenho-me sentido relaxado?',
      'ro': 'M-am simțit relaxat?',
      'tr': 'Kendimi rahatlamış hissediyorum?',
    },
    '5q8qybvp': {
      'en': 'I’ve been feeling interested in other people?',
      'es': '¿He sentido interés por los demás?',
      'hu': 'Érdeklődtem mások iránt?',
      'it': 'Mi sono sentito interessato ad altre persone?',
      'pt': 'Tenho-me sentido interessado pelas\noutras pessoas?',
      'ro': 'M-am simțit interesat de alți oameni?',
      'tr': 'Diğer insanlara karşı ilgiliyim?',
    },
    'ozkdtb5y': {
      'en': 'I’ve had energy to spare?',
      'es': '¿He tenido energía de sobra?',
      'hu': 'Volt tartalék energiám?',
      'it': 'Ho avuto energia da risparmiare?',
      'pt': 'Tenho tido energia de sobra?',
      'ro': 'Am avut energie de pierdut?',
      'tr': 'Farklı işlere zaman ayırabilecek enerjim var?',
    },
    'k5ofc2on': {
      'en': 'I’ve been dealing with problems well?',
      'es': '¿He afrontado bien los problemas?',
      'hu': 'Jól kezeltem a problémákat?',
      'it': 'Ho affrontato bene i problemi?',
      'pt': 'Tenho lidado bem com os problemas?',
      'ro': 'M-am descurcat bine cu problemele?',
      'tr': 'Sorunlarla iyi bir şekilde başa çıkabilirim?',
    },
    'zd2otd9b': {
      'en': 'I’ve been thinking clearly?',
      'es': '¿He podido pensar con claridad?',
      'hu': 'Tisztán gondolkodtam?',
      'it': 'Ho pensato chiaramente?',
      'pt': 'Tenho conseguido pensar de forma clara?',
      'ro': 'M-am gândit clar?',
      'tr': 'Açık ve net bir şekilde düşünebiliyorum?',
    },
    '4e3q8305': {
      'en': 'I’ve been feeling good about myself?',
      'es': '¿Me he sentido bien conmigo mismo/a?',
      'hu': 'Jól éreztem magam?',
      'it': 'Mi sono sentito bene con me stesso?',
      'pt': 'Tenho-me sentido bem comigo mesmo?',
      'ro': 'M-am simțit bine cu mine?',
      'tr': 'Kendimden memnunum?',
    },
    'b6lthtec': {
      'en': 'I’ve been feeling close to other people?',
      'es': '¿Me he sentido cercano/a a los demás?',
      'hu': 'Közel éreztem magam másokhoz?',
      'it': 'Mi sono sentito vicino ad altre persone?',
      'pt': 'Tenho-me sentido próximo de outras\npessoas?',
      'ro': 'M-am simțit aproape de alți oameni?',
      'tr': 'Kendime güveniyorum?',
    },
    'g6fohz2r': {
      'en': 'I’ve been feeling confident?',
      'es': '¿Me he sentido seguro/a (con confianza)?',
      'hu': 'Magabiztosnak éreztem magam?',
      'it': 'Mi sono sentito sicuro?',
      'pt': 'Tenho-me sentido confiante?',
      'ro': 'M-am simțit încrezător?',
      'tr': 'Kendi kararlarımı kendim verebiliyorum?',
    },
    '5gh29r2x': {
      'en': 'I’ve been able to make up  my own mind  about things?',
      'es': '¿He sido capaz de tomar mis propias decisiones?',
      'hu': 'El tudtam dönteni a saját véleményemet a dolgokról?',
      'it': 'Sono stato in grado di prendere una decisione sulle cose?',
      'pt': 'Tenho sido capaz de construir as minhas opiniões sobre as coisas?',
      'ro': 'Am reușit să mă hotăresc despre lucruri?',
      'tr': 'Bazı şeyler hakkında kendi kararımı verebildim mi?',
    },
    'sqzoiq7s': {
      'en': 'I’ve been feeling loved?',
      'es': '¿Me he sentido querido/a?',
      'hu': 'Szeretve éreztem magam?',
      'it': 'Mi sono sentito amato?',
      'pt': 'Tenho-me sentido amado?',
      'ro': 'M-am simțit iubit?',
      'tr': 'Sevildiğimi hissediyorum?',
    },
    'sjg8oidb': {
      'en': 'I’ve been interested in new things?',
      'es': '¿Me he interesado por cosas nuevas?',
      'hu': 'Érdekeltek az új dolgok?',
      'it': 'Sono stato interessato a cose nuove?',
      'pt': 'Tenho-me sentido interessado em coisas novas?',
      'ro': 'M-au interesat lucruri noi?',
      'tr': 'Yeni şeylere karşı ilgiliyim?',
    },
    '5l9bc8pp': {
      'en': 'I’ve been feeling cheerful?',
      'es': '¿Me he sentido alegre?',
      'hu': 'Jókedvűnek éreztem magam?',
      'it': 'Mi sono sentito allegro?',
      'pt': 'Tenho-me sentido alegre?',
      'ro': 'M-am simțit vesel?',
      'tr': 'Neşeli hissediyorum?',
    },
    'gkq5pcxu': {
      'en': 'Delete',
      'es': 'Borrar',
      'hu': 'Töröl',
      'it': 'Eliminare',
      'pt': 'Excluir',
      'ro': 'Șterge',
      'tr': 'Silmek',
    },
    'h36rl586': {
      'en': 'Skills',
      'es': 'Competencias',
      'hu': 'Készségek',
      'it': 'Competenze',
      'pt': 'Habilidades',
      'ro': 'Aptitudini',
      'tr': 'Yetenekler',
    },
    'u6dnsqzb': {
      'en': 'Self-awareness?',
      'es': '¿Autoconciencia?',
      'hu': 'Öntudat?',
      'it': 'Autocoscienza?',
      'pt': 'Autoconsciência?',
      'ro': 'Constiinta de sine?',
      'tr': 'Öz farkındalık?',
    },
    'ifnblsce': {
      'en': 'Self-management?',
      'es': '¿Autogestión?',
      'hu': 'Önálló gazdálkodás?',
      'it': 'Autogestione?',
      'pt': 'Auto Gerenciamento?',
      'ro': 'Managementul de sine?',
      'tr': 'Öz yönetim?',
    },
    'shdk7ab4': {
      'en': 'Responsible decision making?',
      'es': '¿Toma de decisiones responsable?',
      'hu': 'Felelős döntéshozatal?',
      'it': 'Decisione responsabile?',
      'pt': 'Tomada de decisão responsável?',
      'ro': 'Luare responsabilă a deciziilor?',
      'tr': 'Sorumlu karar verme?',
    },
    'xqewvcqp': {
      'en': 'Relationship skills?',
      'es': '¿Habilidades de relación?',
      'hu': 'Párkapcsolati készségek?',
      'it': 'Abilità relazionali?',
      'pt': 'Habilidades de relacionamento?',
      'ro': 'Abilități de relație?',
      'tr': 'İlişki becerileri?',
    },
    'hcb9kupq': {
      'en': 'Social awareness?',
      'es': '¿Conciencia social?',
      'hu': 'Társadalmi tudatosság?',
      'it': 'Consapevolezza sociale?',
      'pt': 'Consciência social?',
      'ro': 'Constientizare sociala?',
      'tr': 'Sosyal farkındalık mı?',
    },
    'jzqzfxbl': {
      'en': 'Delete',
      'es': 'Borrar',
      'hu': 'Töröl',
      'it': 'Eliminare',
      'pt': 'Excluir',
      'ro': 'Șterge',
      'tr': 'Silmek',
    },
    'j610cudu': {
      'en': 'View  Assessment',
      'es': 'Ver evaluación',
      'hu': 'Értékelés megtekintése',
      'it': 'Visualizza valutazione',
      'pt': 'Ver Avaliação',
      'ro': 'Vedeți evaluarea',
      'tr': 'Değerlendirmeyi Görüntüle',
    },
    'mgw8por7': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameCompenciasAval
  {
    'peppsfma': {
      'en': 'Competency Ratings',
      'es': 'Calificaciones de competencia',
      'hu': 'Kompetenciaértékelések',
      'it': 'Valutazioni delle competenze',
      'pt': 'Classificações de Competência',
      'ro': 'Evaluări ale competențelor',
      'tr': 'Yetkinlik Derecelendirmeleri',
    },
    'zv61mbo5': {
      'en': 'Self-awareness',
      'es': 'Autoconciencia',
      'hu': 'Öntudatosság',
      'it': 'Autocoscienza',
      'pt': 'Autoconsciência',
      'ro': 'Constiinta de sine',
      'tr': 'Öz farkındalık',
    },
    'qa9eq2qa': {
      'en': 'Self-management',
      'es': 'Autogestión',
      'hu': 'Önálló gazdálkodás',
      'it': 'Autogestione',
      'pt': 'Auto Gerenciamento',
      'ro': 'Managementul de sine',
      'tr': 'Öz yönetim',
    },
    'cqeuyvtk': {
      'en': 'Responsible Decision Making',
      'es': 'Toma de decisiones responsable',
      'hu': 'Felelős döntéshozatal',
      'it': 'Processo decisionale responsabile',
      'pt': 'Tomada de decisão responsável',
      'ro': 'Luarea responsabilă a deciziilor',
      'tr': 'Sorumlu Karar Verme',
    },
    'p1o0rrhx': {
      'en': 'Relationship Skills',
      'es': 'Habilidades de relación',
      'hu': 'Kapcsolattartási készségek',
      'it': 'Abilità relazionali',
      'pt': 'Habilidades de relacionamento',
      'ro': 'Abilități de relație',
      'tr': 'İlişki Becerileri',
    },
    'upw5qosd': {
      'en': 'Social Awareness',
      'es': 'Conciencia social',
      'hu': 'Társadalmi tudatosság',
      'it': 'Consapevolezza sociale',
      'pt': 'Consciência social',
      'ro': 'Constientizare sociala',
      'tr': 'Sosyal Farkındalık',
    },
    '8cfb12xd': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    'd4ke6swh': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameCompenciasDef
  {
    'r1ua1mah': {
      'en': 'Defined Competences',
      'es': 'Competencias Definidas',
      'hu': 'Meghatározott Kompetenciák',
      'it': 'Competenze Definite',
      'pt': 'Competências definidas',
      'ro': 'Competențe Definite',
      'tr': 'Tanımlanmış Yetkinlikler',
    },
    'bgw8k81t': {
      'en': 'Self-awareness',
      'es': 'Autoconciencia',
      'hu': 'Öntudatosság',
      'it': 'Autocoscienza',
      'pt': 'Autoconsciência',
      'ro': 'Constiinta de Sine',
      'tr': 'Öz Farkındalık',
    },
    'au4q531v': {
      'en': 'Self-management',
      'es': 'Autogestión',
      'hu': 'Önálló Gazdálkodás',
      'it': 'Autogestione',
      'pt': 'Auto Gerenciamento',
      'ro': 'Managementul de Sine',
      'tr': 'Öz yönetim',
    },
    'a2yr9m61': {
      'en': 'Responsible Decision Making',
      'es': 'Toma de Decisiones Responsable',
      'hu': 'Felelős Döntéshozatal',
      'it': 'Processo Decisionale Responsabile',
      'pt': 'Tomada de Decisão Responsável',
      'ro': 'Luarea responsabilă a Deciziilor',
      'tr': 'Sorumlu Karar Verme',
    },
    'nnu6ytp4': {
      'en': 'Relationship Skills',
      'es': 'Habilidades de Relación',
      'hu': 'Kapcsolattartási Készségek',
      'it': 'Abilità Relazionali',
      'pt': 'Habilidades de Relacionamento',
      'ro': 'Abilități de Relație',
      'tr': 'İlişki Becerileri',
    },
    'twjzyt18': {
      'en': 'Social Awareness',
      'es': 'Conciencia Social',
      'hu': 'Társadalmi Tudatosság',
      'it': 'Consapevolezza Sociale',
      'pt': 'Consciência Social',
      'ro': 'Constientizare Sociala',
      'tr': 'Sosyal Farkındalık',
    },
    '1e3e0uu1': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    '2veink44': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameMenu
  {
    '39bsvhrj': {
      'en': 'Game Overview',
      'es': 'Resumen del juego',
      'hu': 'Játék áttekintése',
      'it': 'Panoramica del gioco',
      'pt': 'Visão geral do jogo',
      'ro': 'Prezentare generală a jocului',
      'tr': 'Oyuna Genel Bakış',
    },
    '8jzy7pah': {
      'en': 'Set Up',
      'es': 'Preparación',
      'hu': 'Játéktér',
      'it': 'Impostare',
      'pt': 'Configuração',
      'ro': 'Înființat',
      'tr': 'Düzen',
    },
    'ezipth22': {
      'en': 'Competency Ratings',
      'es': 'Competencias',
      'hu': 'Kompetenciaértékelés',
      'it': 'Valutazioni Delle Competenze',
      'pt': 'Classificações de Competência',
      'ro': 'Evaluări ale Competențelor',
      'tr': 'Yeterlilik Dereceleri',
    },
    'qgbabp3p': {
      'en': 'Adaptations',
      'es': 'Adaptaciones',
      'hu': 'Változatok',
      'it': 'Adattamenti',
      'pt': 'Adaptações',
      'ro': 'Adaptări',
      'tr': 'Uyarlamalar',
    },
    'o077n9jp': {
      'en': 'Reflection',
      'es': 'Reflexión',
      'hu': ' Feldolgozás',
      'it': 'Riflessione',
      'pt': 'Reflexão',
      'ro': 'Reflecţie',
      'tr': 'Yansıtma',
    },
    'zrxssf97': {
      'en': 'Video',
      'es': 'Vídeo',
      'hu': 'Videó',
      'it': 'video',
      'pt': 'Vídeo',
      'ro': 'Video',
      'tr': 'Video',
    },
    'cl4icfes': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    'qmkdqe37': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameVisaoJogo
  {
    'yn4qunby': {
      'en': 'Game Overview',
      'es': 'Información General del Juego',
      'hu': 'Játék Áttekintése',
      'it': 'Panoramica del Gioco',
      'pt': 'Visão Geral do Jogo',
      'ro': 'Prezentare Generală a Jocului',
      'tr': 'Oyun Değerlendirmesi',
    },
    'weteyquo': {
      'en': 'Set Up',
      'es': 'Configurar',
      'hu': 'Beállít',
      'it': 'Preparazione',
      'pt': 'Configuração',
      'ro': 'Înființat',
      'tr': 'Kurmak',
    },
    '3pzljhid': {
      'en': 'Challenge',
      'es': 'Desafío',
      'hu': 'Kihívás',
      'it': 'Sfida',
      'pt': 'Desafio',
      'ro': 'Provocare',
      'tr': 'Meydan Okuma',
    },
    'bd0lxiqe': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    'pwv7x0v2': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameConfiguracao
  {
    'ohskmrvp': {
      'en': 'Set Up',
      'es': 'Configurar',
      'hu': 'Beállít',
      'it': 'Preparazione',
      'pt': 'Configuração',
      'ro': 'Înființat',
      'tr': 'Kurmak',
    },
    'hpfge392': {
      'en': 'Equipment',
      'es': 'Equipo',
      'hu': 'Felszerelés',
      'it': 'Attrezzatura',
      'pt': 'Equipamento',
      'ro': 'Echipamente',
      'tr': 'Teçhizat',
    },
    'b19672v9': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    'soou7efi': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameCompetenciaMeno
  {
    'eo89na5e': {
      'en': 'Competences',
      'es': 'Competencias',
      'hu': 'Kompetenciák',
      'it': 'Competenze',
      'pt': 'Competências',
      'ro': 'Competențe',
      'tr': 'Yetkinlikler',
    },
    'ujvgfsfh': {
      'en': 'Defined Competences',
      'es': 'Competencias Definidas',
      'hu': 'Kompetenciák Meghatározása',
      'it': 'Competenze Definite',
      'pt': 'Competências Definidas',
      'ro': 'Competențe Definite',
      'tr': 'Tanımlanmış Yeterlilikler',
    },
    'ekqzl3ds': {
      'en': 'Competency Ratings',
      'es': 'Calificaciones de Competencia',
      'hu': 'Ezen kompetenciák Értékelése',
      'it': 'Valutazioni delle Competenze',
      'pt': 'Classificações de Competência',
      'ro': 'Evaluări ale Competențelor',
      'tr': 'Yeterlilik Dereceleri',
    },
    'gbj12m4o': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    'vxuoxefj': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameAdaptacao
  {
    'pj5b0xj1': {
      'en': 'Adaptations',
      'es': 'Adaptaciones',
      'hu': 'Adaptációk',
      'it': 'Adattamenti',
      'pt': 'Adaptações',
      'ro': 'Adaptări',
      'tr': 'Uyarlamalar',
    },
    'lz8c3qur': {
      'en': 'To Simplify',
      'es': 'Disminuir la Dificultad ',
      'hu': 'Egyszerűsítés',
      'it': 'Per Semplificare',
      'pt': 'Para Simplificar',
      'ro': 'A Simplifica',
      'tr': 'Basitleştirmek için',
    },
    'pmqrsn21': {
      'en': 'To Progress',
      'es': 'Aumentar la Dificultad',
      'hu': 'Nehezítés',
      'it': 'Progredire',
      'pt': 'Para Progredir',
      'ro': 'Să Progreseze',
      'tr': 'Geliştirmek için',
    },
    'sed37tim': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    'nq9acwj1': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameEquipamento
  {
    '35wkeeao': {
      'en': 'Equipment',
      'es': 'Equipo',
      'hu': 'Felszerelés',
      'it': 'Attrezzatura',
      'pt': 'Equipamento',
      'ro': 'Echipamente',
      'tr': 'Teçhizat',
    },
    'dz9kf2vp': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    'vsjxgf2q': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // GameReflecao
  {
    'zzxgzh33': {
      'en': 'Reflection',
      'es': 'Reflexión',
      'hu': 'Visszaverődés',
      'it': 'Riflessione',
      'pt': 'Reflexão',
      'ro': 'Reflecţie',
      'tr': 'Yansıtma',
    },
    'f1woacxs': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    'q996ilhq': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // Gameviedeo
  {
    'tx2guwdt': {
      'en': 'Video',
      'es': 'Video',
      'hu': 'Videó',
      'it': 'Video',
      'pt': 'Vídeo',
      'ro': 'Video',
      'tr': 'Video',
    },
    'phub8by0': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
    '6ersfk5f': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // Dashboard
  {
    '8a6fv4z8': {
      'en': 'Student',
      'es': 'Estudiante',
      'hu': 'Résztvevő',
      'it': 'Studente ',
      'pt': 'Estudante',
      'ro': 'elevilor',
      'tr': 'Öğrenci',
    },
    'f6jdg9aa': {
      'en': 'Age:',
      'es': 'Edad:',
      'hu': 'Életkor:',
      'it': 'Età:',
      'pt': 'Idade:',
      'ro': 'Vârstă:',
      'tr': 'Yaş:',
    },
    'j91f5o2u': {
      'en': 'Gender',
      'es': 'Género',
      'hu': 'Nem',
      'it': 'Genere ',
      'pt': 'Genero',
      'ro': 'Gen',
      'tr': 'Cinsiyet',
    },
    '9fx2zujg': {
      'en': 'Questions',
      'es': 'Preguntas',
      'hu': 'Kérdések',
      'it': 'Domande ',
      'pt': 'Questões',
      'ro': 'Întrebări',
      'tr': 'Sorular',
    },
    'l9asqr81': {
      'en': 'Rating',
      'es': 'Evaluación',
      'hu': 'Értékelés',
      'it': 'Valutazione',
      'pt': 'Nota',
      'ro': 'Evaluare',
      'tr': 'Değerlendirme',
    },
    '4b4nrid3': {
      'en': 'Data View',
      'es': 'Vista de datos',
      'hu': 'Adatok megtekintése',
      'it': 'Visione dei Dati ',
      'pt': 'Dados',
      'ro': 'Vizualizare date',
      'tr': 'Veri görünümü',
    },
    'x3nhzavu': {
      'en': 'Home',
      'es': 'INICIO',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // DashboardClass
  {
    'rk6tj17f': {
      'en': 'Class',
      'es': 'Clase',
      'hu': 'Csoport',
      'it': 'Classe',
      'pt': 'Turma',
      'ro': 'clasei',
      'tr': 'Sınıf',
    },
    'bis4m5h6': {
      'en': 'Questions',
      'es': 'Preguntas',
      'hu': 'Kérdések',
      'it': 'Domande',
      'pt': 'Questões',
      'ro': 'Întrebări',
      'tr': 'Sorular',
    },
    '94tzo6ox': {
      'en': 'Rating',
      'es': 'Evaluación',
      'hu': 'Értékelés',
      'it': 'Valutazione',
      'pt': 'Nota',
      'ro': 'Evaluar',
      'tr': 'Değerlendirme',
    },
    'zu9rrwsu': {
      'en': 'Data View',
      'es': 'Vista de datos',
      'hu': 'Adatok megtekintése',
      'it': 'Visione dei Dati ',
      'pt': 'Dados',
      'ro': 'Vizualizare date',
      'tr': 'Veri görünümü',
    },
    '7lbizjt0': {
      'en': 'Home',
      'es': 'INICIO',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // Register
  {
    'ws558ev3': {
      'en': 'Register Participants',
      'es': 'Registro/Lista',
      'hu': 'Regisztráció/Lista',
      'it': 'Registro/Elenco',
      'pt': 'Registar Participantes',
      'ro': 'Înregistrare/Lista',
      'tr': 'Kayıt/Liste',
    },
  },
  // Games
  {
    '95rpl7p4': {
      'en': 'Games',
      'es': 'Juegos',
      'hu': 'Játékok',
      'it': 'Giochi',
      'pt': 'Jogos',
      'ro': 'Jocuri',
      'tr': 'Oyunlar',
    },
  },
  // Exit
  {
    '4nueaumw': {
      'en': 'Exit',
      'es': 'Salida',
      'hu': 'Kilépés',
      'it': 'Uscita',
      'pt': 'Sair',
      'ro': 'Ieșire',
      'tr': 'Çıkış Yap',
    },
  },
  // ClassA
  {
    '4pk3um6f': {
      'en': 'Class  Evaluation',
      'es': 'Evaluación de la clase',
      'hu': 'Osztály értékelése',
      'it': 'Valutazione di classe',
      'pt': 'Avaliação da Turma',
      'ro': 'Evaluarea clasei',
      'tr': 'Sınıf Değerlendirmesi',
    },
  },
  // StudentA
  {
    'vggs6s1e': {
      'en': 'Student Evaluation',
      'es': 'Evaluación de estudiante',
      'hu': 'Hallgatói értékelés',
      'it': 'Valutazione degli studenti',
      'pt': 'Avaliação do Aluno',
      'ro': 'Evaluarea elevilor',
      'tr': 'Öğrenci Değerlendirmesi',
    },
  },
  // StudentRe
  {
    'hef4nawh': {
      'en': 'New Student',
      'es': 'Estudiante nuevo',
      'hu': 'Új diák',
      'it': 'Nuovo studente',
      'pt': 'Novo estudante',
      'ro': 'Student nou',
      'tr': 'Yeni Öğrenci ',
    },
    'a0k59zgg': {
      'en': 'Name',
      'es': 'Nombre',
      'hu': 'Név',
      'it': 'Nome',
      'pt': 'Nome',
      'ro': 'Nume',
      'tr': 'İsim',
    },
    'bkjrwkc3': {
      'en': 'Age',
      'es': 'Edad',
      'hu': 'Kor',
      'it': 'Età',
      'pt': 'Idade',
      'ro': 'Vârstă',
      'tr': 'Yaş',
    },
    'xddxmv6b': {
      'en': 'Male',
      'es': 'Masculino',
      'hu': 'Férfi',
      'it': 'Maschio',
      'pt': 'Masculino',
      'ro': 'Masculin',
      'tr': 'Erkek',
    },
    'nfnycwrf': {
      'en': 'Female',
      'es': 'No respondo',
      'hu': 'Nem válaszol',
      'it': 'Non rispondere',
      'pt': 'Não respondo',
      'ro': 'Nu Răspunde',
      'tr': 'Cevap Yok',
    },
    'rfym8q5v': {
      'en': 'Other',
      'es': 'Femenino',
      'hu': 'Női',
      'it': 'Femmina',
      'pt': 'feminino',
      'ro': 'Femeie',
      'tr': 'Dişi',
    },
    'oe5qjder': {
      'en': 'Unknown',
      'es': 'no binario',
      'hu': 'Nem bináris',
      'it': 'Non binario',
      'pt': 'Não Binário',
      'ro': 'Non binar',
      'tr': 'İkili Olmayan',
    },
    'r5s429b4': {
      'en': 'Cancel',
      'es': 'Cancelar',
      'hu': 'Megszünteti',
      'it': 'Annulla',
      'pt': 'Cancelar',
      'ro': 'Anulare',
      'tr': 'İptal etmek',
    },
    'wrwhw62r': {
      'en': 'Save',
      'es': 'Guardar',
      'hu': 'Megment',
      'it': 'Salva',
      'pt': 'Save',
      'ro': 'salva',
      'tr': 'Gönder',
    },
  },
  // Homes
  {
    'gyup2qxw': {
      'en': 'Home',
      'es': 'Inicio',
      'hu': 'Főoldal',
      'it': 'Casa',
      'pt': 'Home',
      'ro': 'Acasă',
      'tr': 'Ana Menü',
    },
  },
  // ClassAadd
  {
    'j62u84qx': {
      'en': 'Class assessment',
      'es': 'Evaluación de la clase',
      'hu': 'Osztály értékelése',
      'it': 'Valutazione di classe',
      'pt': 'Avaliação da Turma',
      'ro': 'Evaluarea clasei',
      'tr': 'sınıf değerlendirmesi',
    },
    'kf4fv6n3': {
      'en': 'Self-awareness?',
      'es': '¿Autoconciencia?',
      'hu': 'Öntudat?',
      'it': 'Autocoscienza?',
      'pt': 'Autoconsciência?',
      'ro': 'Constiinta de sine?',
      'tr': 'Öz farkındalık?',
    },
    'r4rv9dzo': {
      'en': 'Self-management?',
      'es': '¿Autogestión?',
      'hu': 'Önálló gazdálkodás?',
      'it': 'Autogestione?',
      'pt': 'Auto Gerenciamento?',
      'ro': 'Managementul de sine?',
      'tr': 'Öz yönetim?',
    },
    'ray0u87s': {
      'en': 'Responsible decision making?',
      'es': '¿Toma de decisiones responsable?',
      'hu': 'Felelős döntéshozatal?',
      'it': 'Decisione responsabile?',
      'pt': 'Tomada de decisão responsável?',
      'ro': 'Luare responsabilă a deciziilor?',
      'tr': 'Sorumlu karar verme?',
    },
    '1e8j3mib': {
      'en': 'Relationship skills?',
      'es': '¿Habilidades de relación?',
      'hu': 'Párkapcsolati készségek?',
      'it': 'Abilità relazionali?',
      'pt': 'Habilidades de relacionamento?',
      'ro': 'Abilități de relație?',
      'tr': 'İlişki becerileri?',
    },
    'tvoccm9z': {
      'en': 'Social awareness?',
      'es': '¿Conciencia social?',
      'hu': 'Társadalmi tudatosság?',
      'it': 'Consapevolezza sociale?',
      'pt': 'Consciência social?',
      'ro': 'Constientizare sociala?',
      'tr': 'Sosyal farkındalık mı?',
    },
    'bcw4fl2v': {
      'en': 'Description',
      'es': 'Descripción',
      'hu': 'Leírás',
      'it': 'Descrizione',
      'pt': 'Descrição',
      'ro': 'Descriere',
      'tr': 'Tanım',
    },
    'bvdvpgym': {
      'en': 'Cancel',
      'es': 'Cancelar',
      'hu': 'Megszünteti',
      'it': 'Annulla',
      'pt': 'Cancelar',
      'ro': 'Anulare',
      'tr': 'İptal etmek',
    },
    'ukv4pgvf': {
      'en': 'Save',
      'es': 'Guardar',
      'hu': 'Megment',
      'it': 'Salva',
      'pt': 'Salve ',
      'ro': 'salva',
      'tr': 'Kaydetmek',
    },
  },
  // ClassAView
  {
    'mhed8hy6': {
      'en': 'Class assessment',
      'es': 'Evaluación de la clase',
      'hu': 'Osztály értékelése',
      'it': 'Valutazione di classe',
      'pt': 'Avaliação da Turma',
      'ro': 'Evaluarea clasei',
      'tr': 'sınıf değerlendirmesi',
    },
    'nrdfsd9g': {
      'en': 'Self-awareness?',
      'es': '¿Autoconciencia?',
      'hu': 'Öntudat?',
      'it': 'Autocoscienza?',
      'pt': 'Autoconsciência?',
      'ro': 'Constiinta de sine?',
      'tr': 'Öz-farkındalık?',
    },
    'ow37zq6q': {
      'en': 'Self-management?',
      'es': '¿Autogestión?',
      'hu': 'Önálló gazdálkodás?',
      'it': 'Autogestione?',
      'pt': 'Auto Gerenciamento?',
      'ro': 'Managementul de sine?',
      'tr': 'Öz-yönetim?',
    },
    'hk56gmxv': {
      'en': 'Responsible decision making?',
      'es': '¿Toma de decisiones responsable?',
      'hu': 'Felelős döntéshozatal?',
      'it': 'Decisione responsabile?',
      'pt': 'Tomada de decisão responsável?',
      'ro': 'Luare responsabilă a deciziilor?',
      'tr': 'Sorumlu Karar Verme?',
    },
    'sazv02g9': {
      'en': 'Relationship skills?',
      'es': '¿Habilidad de relación?',
      'hu': 'Párkapcsolati készségek?',
      'it': 'Abilità relazionali?',
      'pt': 'Habilidades de relacionamento?',
      'ro': 'Abilități de relație?',
      'tr': 'İlişki Becerileri?',
    },
    '58e2odqt': {
      'en': 'Social awareness?',
      'es': '¿Conciencia social?',
      'hu': 'Társadalmi tudatosság?',
      'it': 'Consapevolezza sociale?',
      'pt': 'Consciência social?',
      'ro': 'Constientizare sociala?',
      'tr': 'osyal Farkındalık?',
    },
    'i53dlrvr': {
      'en': 'Description',
      'es': 'Descripción',
      'hu': 'Leírás',
      'it': 'Descrizione',
      'pt': 'Descrição',
      'ro': 'Descriere',
      'tr': 'Tanım',
    },
  },
  // Web
  {
    '6o7p1d44': {
      'en': 'Dashboard',
      'es': 'Salida',
      'hu': 'Kijárat',
      'it': 'Uscita',
      'pt': 'Sair',
      'ro': 'Ieșire',
      'tr': 'Çıkış Yap',
    },
  },
  // Miscellaneous
  {
    'ev6v36ue': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'ddhr5z07': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'pjoeplja': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'rmkf5x1n': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'f4oxbko3': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'ga3ch120': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    '7gnzs38r': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'x8edng66': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'xn27d9mi': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'e9uoord4': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'yxbm2656': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'hpvrn7zg': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    '8upet1ck': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'jfcagwtc': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'c3sfnb6h': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    '3gc5j3f7': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'f9qfgeua': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    '68350zk2': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    'bwmg6ynx': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
    '1n3rbxv4': {
      'en': '',
      'es': '',
      'hu': '',
      'it': '',
      'pt': '',
      'ro': '',
      'tr': '',
    },
  },
].reduce((a, b) => a..addAll(b));
